#!/bin/bash

# enter path to darep.jar here
DAREP_JAR="./darep.jar"

# try to find the java-binary and echo the path to it
# return 0 if found, 1 if not.
function find_java_bin() {

	# maybe java is included in $PATH ?
	local JAVABIN=$(which java)

	# if not, try $JAVA_HOME variable
	if [ -z "$JAVABIN" -a -n "$JAVA_HOME" ]; then
		local JAVABIN="$JAVA_HOME/bin/java"
	fi


	# echo path to java-binary if found and executable
	# else return 1
	if [ -x "$JAVABIN" ]; then
		echo "$JAVABIN"
		return 0
	else
		return 1
	fi

}

################
# begin script #
################

JAVA_BIN=$(find_java_bin)

if [ $? -ne 0 ]; then
	echo "Could not find java-executable. Try including it in \$PATH or setting \$JAVA_HOME"
	exit 1
else
	# call the data-repository binary with given arguments
	$JAVA_BIN -jar $DAREP_JAR "$@"
fi
